version: "3.8"
services:
  integratedproject:
    image: penbeaa/integratedproject:latest
    build: .
    container_name: integratedproject
    ports:
      - "4000:3000"
    environment:
       - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "app.js"]
